name: Update Next Development Version
run-name: Update next development version after release

on:
  push:
    tags:
      - '*'

jobs:
  update-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update to next SNAPSHOT version
        run: |
          # 現在のタグからバージョンを取得
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          
          # バージョンをパース
          IFS='.' read -r -a VERSION_PARTS <<< "$RELEASE_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          
          # 次のSNAPSHOTバージョンを設定（デフォルトはpatchをインクリメント）
          NEXT_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))-SNAPSHOT"
          
          # バージョンを更新
          mvn versions:set -DnewVersion=${NEXT_VERSION} -DgenerateBackupPoms=false
          
          # コミットしてプッシュ
          git add pom.xml
          git commit -m "Prepare next development version ${NEXT_VERSION}"
          git push origin develop
