name: Create Release PR
on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Create release branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          RELEASE_VERSION=${CURRENT_VERSION%-SNAPSHOT}
          
          git checkout -b release/${RELEASE_VERSION}
          
          mvn versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false
          git add pom.xml
          git commit -m "Prepare release ${RELEASE_VERSION}"
          git push origin release/${RELEASE_VERSION}
          
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Create PR with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head release/${{ env.RELEASE_VERSION }} \
            --title "Release ${{ env.RELEASE_VERSION }}" \
            --body "Release ${{ env.RELEASE_VERSION }}"
