name: Test
on:
  pull_request:
    paths: [ 'src/main/java/com/github/teruyukisuda/**/*.java' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Print cache info
        run: |
          echo "M2_HOME: $M2_HOME"
          echo "Maven repository location:"
          mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout

      - run: mvn test
