# javaソースが変更されたPRに対してテストを実行する
name: Javaソース変更検証
run-name: PR \#${{ github.event.pull_request.number }} のJavaソース変更をテスト
on:
  pull_request:
    paths: [ 'src/main/java/com/github/teruyukisuda/**/*.java' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - run: mvn test  

