name: Test
on:
  pull_request:
    paths: [ 'src/main/java/com/github/teruyukisuda/**/*.java' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        id: maven-cache  # IDを追加してキャッシュヒットを確認できるようにする
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Print cache status
        run: echo "Cache hit - ${{ steps.maven-cache.outputs.cache-hit }}"

      - run: mvn test  

