# mainブランチへのPRでバージョン番号の変更を検証するワークフロー
# リリース準備においてpom.xmlのバージョンが必ず更新されていることを確認します
name: リリース用バージョン変更検証
run-name: リリース用バージョン変更検証

on:
  pull_request:
    branches: [ main ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: バージョン変更の確認
        run: |
          CURRENT_VERSION=$(grep -m 1 "<version>" pom.xml | sed 's/[<>]/|/g' | cut -d '|' -f 3)
          git checkout origin/${{ github.base_ref }}
          PREVIOUS_VERSION=$(grep -m 1 "<version>" pom.xml | sed 's/[<>]/|/g' | cut -d '|' -f 3)
          
          if [ "$CURRENT_VERSION" = "$PREVIOUS_VERSION" ]; then
            echo "警告: pom.xml のバージョンが変更されていません。mainブランチへのPRではバージョン更新が必要です。"
            exit 1
          fi
          
          echo "バージョン変更を確認: $PREVIOUS_VERSION -> $CURRENT_VERSION"
